# Generated by Django 5.2.2 on 2025-06-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Enter the text', max_length=50, unique=True)),
                ('is_solved', models.BooleanField(default=False, help_text='Check if this word has been solved by a user.')),
            ],
            options={
                'verbose_name_plural': 'Words',
                'ordering': ['text'],
            },
        ),
    ]
