# Generated by Django 5.2.2 on 2025-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_word_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(help_text='Enter the text', max_length=50),
        ),
    ]
